#!/usr/bin/env bash
# Displays information regarding domains and subdomains
print_sub() {
	if [[ -n $2 ]]; then
		local subdomains=$2
	else
		local subdomains=("www" "1b-01" "web-01" "web-02")
	fi
	for address in "${subdomains[@]}"
	do
		full_domain="$address"."$1"
		result=$(dig +noall +answer "$full_domain")
		record=$(echo "$result" | awk '{print$4}')
		dest=$(echo "$result" | awk '{print$5}')
		echo "The subdomain $address is a $record record and points to $dest"
	done;

}
domain="$1"
sub="$2"
if [[ -n $domain ]]; then
	print_sub "$domain" "$sub"
else
	exit
fi

