#!/usr/bin/env bash
#Script is using scp to transfer a file from my client to the server
FILE="$1"
IP="$2"
USR="$3"
PATH_TO_SSH_KEY="$4"
DEST="~"
#executuing scp command with relevant flags
scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$FILE" "$USR@$IP:$DEST"
