#!/usr/bin/env bash
#Installs nginx web server in my server
#Fetch all updates
apt-get update
apt-get -y install nginx

#Open port 80 for server toaccept requests
ufw allow 'Nginx HTTP'

#Change default page when request is made to nginx root
# Create the file
mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
line1='server {'
line2='listen 80;'
line3='location / {'
line4='root /var/www/html;'
line5='index index.html;'
line6='}'
line7='}'
echo -e "$line1\n\t$line2\n\n\t$line3\n\t\t$line4\n\t\t$line5\n\t$line6\n$line7\n" > /etc/nginx/sites-available/default
#configure location /redirect_me to redirect permanently to a new page
line1='location /redirect_me {'
line2='return 301 https://www.youtube.com;'
line3='}'
sed -i "/location \/ {/i \ \t$line1\n\t\t$line2\n\t$line3\n" /etc/nginx/sites-available/default

#create the symbolic link sites-enabled/default if not created
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

#Restart Nginx
sudo service nginx restart
