#!/usr/bin/env bash
#This script prints "Best School" 10 times and adds bad luck and good luck
num=1

while [ $num -lt 11 ];
do
	if [ $num -eq 4 ]
	then
		echo "bad luck"
	elif [ $num -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((num++))
done
