#!/usr/bin/env bash
#changes ip address of localhost from 127.0.0.1 to 127.0.0.2
cp /etc/hosts new_hosts
sed -i 's/^.*localhost$/127.0.0.2	localhost/g' new_hosts
#changes ip address of facebook from to 8.8.8.8
printf "8.8.8.8\tfacebook.com" >> new_hosts
sed -if 's/^.*facebook.com$/8.8.8.8	facebook.com/g' new_hosts
#modify the /etc/hosts
cp -f new_hosts /etc/hosts
